// Curated set of major airports for client-side origin/destination
// typeahead. Matching is done against code, city, and airport name so
// a search like "hyder", "hyd", or "rajiv" all resolve to HYD.
export const AIRPORTS = [
    { code: 'HYD', city: 'Hyderabad', name: 'Rajiv Gandhi International', country: 'India' },
    { code: 'DEL', city: 'Delhi', name: 'Indira Gandhi International', country: 'India' },
    { code: 'BOM', city: 'Mumbai', name: 'Chhatrapati Shivaji Maharaj International', country: 'India' },
    { code: 'BLR', city: 'Bengaluru', name: 'Kempegowda International', country: 'India' },
    { code: 'MAA', city: 'Chennai', name: 'Chennai International', country: 'India' },
    { code: 'CCU', city: 'Kolkata', name: 'Netaji Subhas Chandra Bose International', country: 'India' },
    { code: 'PNQ', city: 'Pune', name: 'Pune Airport', country: 'India' },
    { code: 'AMD', city: 'Ahmedabad', name: 'Sardar Vallabhbhai Patel International', country: 'India' },
    { code: 'COK', city: 'Kochi', name: 'Cochin International', country: 'India' },
    { code: 'GOI', city: 'Goa', name: 'Dabolim Airport', country: 'India' },
    { code: 'JAI', city: 'Jaipur', name: 'Jaipur International', country: 'India' },
    { code: 'LKO', city: 'Lucknow', name: 'Chaudhary Charan Singh International', country: 'India' },
    { code: 'IXC', city: 'Chandigarh', name: 'Chandigarh Airport', country: 'India' },
    { code: 'VNS', city: 'Varanasi', name: 'Lal Bahadur Shastri Airport', country: 'India' },
    { code: 'PAT', city: 'Patna', name: 'Jay Prakash Narayan Airport', country: 'India' },
    { code: 'VTZ', city: 'Visakhapatnam', name: 'Visakhapatnam Airport', country: 'India' },
    { code: 'DXB', city: 'Dubai', name: 'Dubai International', country: 'UAE' },
    { code: 'AUH', city: 'Abu Dhabi', name: 'Zayed International', country: 'UAE' },
    { code: 'DOH', city: 'Doha', name: 'Hamad International', country: 'Qatar' },
    { code: 'SHJ', city: 'Sharjah', name: 'Sharjah International', country: 'UAE' },
    { code: 'RUH', city: 'Riyadh', name: 'King Khalid International', country: 'Saudi Arabia' },
    { code: 'JED', city: 'Jeddah', name: 'King Abdulaziz International', country: 'Saudi Arabia' },
    { code: 'KWI', city: 'Kuwait City', name: 'Kuwait International', country: 'Kuwait' },
    { code: 'MCT', city: 'Muscat', name: 'Muscat International', country: 'Oman' },
    { code: 'SIN', city: 'Singapore', name: 'Changi Airport', country: 'Singapore' },
    { code: 'KUL', city: 'Kuala Lumpur', name: 'Kuala Lumpur International', country: 'Malaysia' },
    { code: 'BKK', city: 'Bangkok', name: 'Suvarnabhumi Airport', country: 'Thailand' },
    { code: 'HKG', city: 'Hong Kong', name: 'Hong Kong International', country: 'Hong Kong' },
    { code: 'NRT', city: 'Tokyo', name: 'Narita International', country: 'Japan' },
    { code: 'HND', city: 'Tokyo', name: 'Haneda Airport', country: 'Japan' },
    { code: 'ICN', city: 'Seoul', name: 'Incheon International', country: 'South Korea' },
    { code: 'PVG', city: 'Shanghai', name: 'Pudong International', country: 'China' },
    { code: 'PEK', city: 'Beijing', name: 'Capital International', country: 'China' },
    { code: 'CAN', city: 'Guangzhou', name: 'Baiyun International', country: 'China' },
    { code: 'TPE', city: 'Taipei', name: 'Taoyuan International', country: 'Taiwan' },
    { code: 'MNL', city: 'Manila', name: 'Ninoy Aquino International', country: 'Philippines' },
    { code: 'CGK', city: 'Jakarta', name: 'Soekarno-Hatta International', country: 'Indonesia' },
    { code: 'DPS', city: 'Denpasar', name: 'Ngurah Rai International', country: 'Indonesia' },
    { code: 'SYD', city: 'Sydney', name: 'Kingsford Smith Airport', country: 'Australia' },
    { code: 'MEL', city: 'Melbourne', name: 'Melbourne Airport', country: 'Australia' },
    { code: 'BNE', city: 'Brisbane', name: 'Brisbane Airport', country: 'Australia' },
    { code: 'PER', city: 'Perth', name: 'Perth Airport', country: 'Australia' },
    { code: 'AKL', city: 'Auckland', name: 'Auckland Airport', country: 'New Zealand' },
    { code: 'LHR', city: 'London', name: 'Heathrow Airport', country: 'United Kingdom' },
    { code: 'LGW', city: 'London', name: 'Gatwick Airport', country: 'United Kingdom' },
    { code: 'MAN', city: 'Manchester', name: 'Manchester Airport', country: 'United Kingdom' },
    { code: 'CDG', city: 'Paris', name: 'Charles de Gaulle Airport', country: 'France' },
    { code: 'ORY', city: 'Paris', name: 'Orly Airport', country: 'France' },
    { code: 'FRA', city: 'Frankfurt', name: 'Frankfurt Airport', country: 'Germany' },
    { code: 'MUC', city: 'Munich', name: 'Munich Airport', country: 'Germany' },
    { code: 'BER', city: 'Berlin', name: 'Brandenburg Airport', country: 'Germany' },
    { code: 'AMS', city: 'Amsterdam', name: 'Schiphol Airport', country: 'Netherlands' },
    { code: 'MAD', city: 'Madrid', name: 'Adolfo Suarez Barajas', country: 'Spain' },
    { code: 'BCN', city: 'Barcelona', name: 'Barcelona-El Prat Airport', country: 'Spain' },
    { code: 'FCO', city: 'Rome', name: 'Leonardo da Vinci-Fiumicino', country: 'Italy' },
    { code: 'MXP', city: 'Milan', name: 'Malpensa Airport', country: 'Italy' },
    { code: 'ZRH', city: 'Zurich', name: 'Zurich Airport', country: 'Switzerland' },
    { code: 'GVA', city: 'Geneva', name: 'Geneva Airport', country: 'Switzerland' },
    { code: 'VIE', city: 'Vienna', name: 'Vienna International', country: 'Austria' },
    { code: 'IST', city: 'Istanbul', name: 'Istanbul Airport', country: 'Turkiye' },
    { code: 'SVO', city: 'Moscow', name: 'Sheremetyevo International', country: 'Russia' },
    { code: 'CPH', city: 'Copenhagen', name: 'Copenhagen Airport', country: 'Denmark' },
    { code: 'ARN', city: 'Stockholm', name: 'Arlanda Airport', country: 'Sweden' },
    { code: 'OSL', city: 'Oslo', name: 'Gardermoen Airport', country: 'Norway' },
    { code: 'HEL', city: 'Helsinki', name: 'Helsinki-Vantaa Airport', country: 'Finland' },
    { code: 'DUB', city: 'Dublin', name: 'Dublin Airport', country: 'Ireland' },
    { code: 'BRU', city: 'Brussels', name: 'Brussels Airport', country: 'Belgium' },
    { code: 'LIS', city: 'Lisbon', name: 'Humberto Delgado Airport', country: 'Portugal' },
    { code: 'ATH', city: 'Athens', name: 'Eleftherios Venizelos', country: 'Greece' },
    { code: 'WAW', city: 'Warsaw', name: 'Chopin Airport', country: 'Poland' },
    { code: 'JFK', city: 'New York', name: 'John F. Kennedy International', country: 'USA' },
    { code: 'EWR', city: 'Newark', name: 'Newark Liberty International', country: 'USA' },
    { code: 'LAX', city: 'Los Angeles', name: 'Los Angeles International', country: 'USA' },
    { code: 'ORD', city: 'Chicago', name: "O'Hare International", country: 'USA' },
    { code: 'SFO', city: 'San Francisco', name: 'San Francisco International', country: 'USA' },
    { code: 'SEA', city: 'Seattle', name: 'Seattle-Tacoma International', country: 'USA' },
    { code: 'ATL', city: 'Atlanta', name: 'Hartsfield-Jackson International', country: 'USA' },
    { code: 'DFW', city: 'Dallas', name: 'Dallas/Fort Worth International', country: 'USA' },
    { code: 'MIA', city: 'Miami', name: 'Miami International', country: 'USA' },
    { code: 'BOS', city: 'Boston', name: 'Logan International', country: 'USA' },
    { code: 'IAD', city: 'Washington', name: 'Dulles International', country: 'USA' },
    { code: 'IAH', city: 'Houston', name: 'George Bush Intercontinental', country: 'USA' },
    { code: 'DEN', city: 'Denver', name: 'Denver International', country: 'USA' },
    { code: 'LAS', city: 'Las Vegas', name: 'Harry Reid International', country: 'USA' },
    { code: 'YYZ', city: 'Toronto', name: 'Pearson International', country: 'Canada' },
    { code: 'YVR', city: 'Vancouver', name: 'Vancouver International', country: 'Canada' },
    { code: 'YUL', city: 'Montreal', name: 'Pierre Elliott Trudeau', country: 'Canada' },
    { code: 'GRU', city: 'Sao Paulo', name: 'Guarulhos International', country: 'Brazil' },
    { code: 'GIG', city: 'Rio de Janeiro', name: 'Galeao International', country: 'Brazil' },
    { code: 'EZE', city: 'Buenos Aires', name: 'Ministro Pistarini', country: 'Argentina' },
    { code: 'MEX', city: 'Mexico City', name: 'Benito Juarez International', country: 'Mexico' },
    { code: 'JNB', city: 'Johannesburg', name: 'O.R. Tambo International', country: 'South Africa' },
    { code: 'CPT', city: 'Cape Town', name: 'Cape Town International', country: 'South Africa' },
    { code: 'CAI', city: 'Cairo', name: 'Cairo International', country: 'Egypt' },
    { code: 'NBO', city: 'Nairobi', name: 'Jomo Kenyatta International', country: 'Kenya' },
    { code: 'LOS', city: 'Lagos', name: 'Murtala Muhammed International', country: 'Nigeria' },
    { code: 'CMB', city: 'Colombo', name: 'Bandaranaike International', country: 'Sri Lanka' },
    { code: 'DAC', city: 'Dhaka', name: 'Hazrat Shahjalal International', country: 'Bangladesh' },
    { code: 'KTM', city: 'Kathmandu', name: 'Tribhuvan International', country: 'Nepal' },
    { code: 'KHI', city: 'Karachi', name: 'Jinnah International', country: 'Pakistan' },
    { code: 'LHE', city: 'Lahore', name: 'Allama Iqbal International', country: 'Pakistan' }
];